/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: CREATED,CCAUTHORIZATIONFAILED,SHIPPED,RECEIVED,AUTHENTICATING,AUTHENTICATED,PAYOUTPENDING,PAYOUTCOMPLETED,SYSTEMFULFILLED,PAYOUTFAILED,SUSPENDED,PENDING
 */

@JsonClass(generateAdapter = false)
enum class ActiveOrderStatus(val value: kotlin.String) {

    @Json(name = "CREATED")
    CREATED("CREATED"),

    @Json(name = "CCAUTHORIZATIONFAILED")
    CCAUTHORIZATIONFAILED("CCAUTHORIZATIONFAILED"),

    @Json(name = "SHIPPED")
    SHIPPED("SHIPPED"),

    @Json(name = "RECEIVED")
    RECEIVED("RECEIVED"),

    @Json(name = "AUTHENTICATING")
    AUTHENTICATING("AUTHENTICATING"),

    @Json(name = "AUTHENTICATED")
    AUTHENTICATED("AUTHENTICATED"),

    @Json(name = "PAYOUTPENDING")
    PAYOUTPENDING("PAYOUTPENDING"),

    @Json(name = "PAYOUTCOMPLETED")
    PAYOUTCOMPLETED("PAYOUTCOMPLETED"),

    @Json(name = "SYSTEMFULFILLED")
    SYSTEMFULFILLED("SYSTEMFULFILLED"),

    @Json(name = "PAYOUTFAILED")
    PAYOUTFAILED("PAYOUTFAILED"),

    @Json(name = "SUSPENDED")
    SUSPENDED("SUSPENDED"),

    @Json(name = "PENDING")
    PENDING("PENDING");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ActiveOrderStatus) "$data" else null

        /**
         * Returns a valid [ActiveOrderStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ActiveOrderStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

