/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param adjustmentType The type of adjustment made
 * @param amount The amount of the adjustment
 * @param percentage The percentage of the adjustment
 */


data class Adjustment (

    /* The type of adjustment made */
    @Json(name = "adjustmentType")
    val adjustmentType: kotlin.String,

    /* The amount of the adjustment */
    @Json(name = "amount")
    val amount: kotlin.String,

    /* The percentage of the adjustment */
    @Json(name = "percentage")
    val percentage: kotlin.String

) {


}

