/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param amount The amount this product is being listed for
 * @param variantId Unique StockX variant ID that this listing is being created for
 * @param currencyCode The currency code this product is being listed in. If not provided, it will default to USD.  Only valid currencies supported on stockx.com are supported via API<br><br>Available values: \"AUD\", \"CAD\", \"CHF\", \"EUR\", \"GBP\", \"HKD\", \"JPY\", \"KRW\", \"MXN\", \"NZD\", \"SGD\", \"USD\"
 * @param expiresAt UTC timestamp representing when this Ask should auto-expire.  If not provided, it will default to 365 days from today.  Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z
 * @param active A flag that defaults to true, activating the listing on the StockX marketplace
 */


data class CreateListingInput (

    /* The amount this product is being listed for */
    @Json(name = "amount")
    val amount: kotlin.String,

    /* Unique StockX variant ID that this listing is being created for */
    @Json(name = "variantId")
    val variantId: kotlin.String,

    /* The currency code this product is being listed in. If not provided, it will default to USD.  Only valid currencies supported on stockx.com are supported via API<br><br>Available values: \"AUD\", \"CAD\", \"CHF\", \"EUR\", \"GBP\", \"HKD\", \"JPY\", \"KRW\", \"MXN\", \"NZD\", \"SGD\", \"USD\" */
    @Json(name = "currencyCode")
    val currencyCode: kotlin.String? = null,

    /* UTC timestamp representing when this Ask should auto-expire.  If not provided, it will default to 365 days from today.  Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z */
    @Json(name = "expiresAt")
    val expiresAt: kotlin.String? = null,

    /* A flag that defaults to true, activating the listing on the StockX marketplace */
    @Json(name = "active")
    val active: kotlin.Boolean? = true

) {


}

