/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import com.cereal.stockx.api.model.GetIngestionItemInput
import com.cereal.stockx.api.model.INGESTIONITEMSTATUS
import com.cereal.stockx.api.model.IngestionItemRejectionDetails
import com.cereal.stockx.api.model.IngestionItemResult

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ingestionId Unique ID used to return the status of an ingestion job.
 * @param status 
 * @param input 
 * @param result The result of the ingestion job if the status is completed.
 * @param partnerProductId The external partner ID provided in the request.
 * @param rejectionDetails The details about its rejection if REJECTED
 * @param createdAt Timestamp when the resource was created.
 * @param updatedAt Timestamp when the resource was last updated.
 */


data class GetIngestionItem (

    /* Unique ID used to return the status of an ingestion job. */
    @Json(name = "ingestionId")
    val ingestionId: kotlin.String,

    @Json(name = "status")
    val status: INGESTIONITEMSTATUS,

    @Json(name = "input")
    val input: GetIngestionItemInput,

    /* The result of the ingestion job if the status is completed. */
    @Json(name = "result")
    val result: IngestionItemResult?,

    /* The external partner ID provided in the request. */
    @Json(name = "partnerProductId")
    val partnerProductId: kotlin.String?,

    /* The details about its rejection if REJECTED */
    @Json(name = "rejectionDetails")
    val rejectionDetails: IngestionItemRejectionDetails?,

    /* Timestamp when the resource was created. */
    @Json(name = "createdAt")
    val createdAt: kotlin.String,

    /* Timestamp when the resource was last updated. */
    @Json(name = "updatedAt")
    val updatedAt: kotlin.String

) {


}

