/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The input for this item that was used when creating the batch
 *
 * @param active Whether this listing is active
 * @param currencyCode The currency code for this listing<br><br>Available values: \"AUD\", \"CAD\", \"CHF\", \"EUR\", \"GBP\", \"HKD\", \"JPY\", \"KRW\", \"MXN\", \"NZD\", \"SGD\", \"USD\"
 * @param variantId The ID of the variant
 * @param expiresAt When this listing expires in UTC
 * @param amount The amount this listing is listed for
 */


data class GetListingCreateBatchItemListingInput (

    /* Whether this listing is active */
    @Json(name = "active")
    val active: kotlin.Boolean?,

    /* The currency code for this listing<br><br>Available values: \"AUD\", \"CAD\", \"CHF\", \"EUR\", \"GBP\", \"HKD\", \"JPY\", \"KRW\", \"MXN\", \"NZD\", \"SGD\", \"USD\" */
    @Json(name = "currencyCode")
    val currencyCode: kotlin.String?,

    /* The ID of the variant */
    @Json(name = "variantId")
    val variantId: kotlin.String?,

    /* When this listing expires in UTC */
    @Json(name = "expiresAt")
    val expiresAt: kotlin.String?,

    /* The amount this listing is listed for */
    @Json(name = "amount")
    val amount: kotlin.String?

) {


}

