/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import com.cereal.stockx.api.model.GetListingUpdateBatchItemListingInput
import com.cereal.stockx.api.model.GetListingUpdateBatchItemResult

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param itemId Unique Item ID
 * @param status The status of this item
 * @param listingInput 
 * @param result 
 * @param error If an item failed to process, the error attribute will contain the error message describing the reason the item failed to process
 */


data class GetListingUpdateBatchItem (

    /* Unique Item ID */
    @Json(name = "itemId")
    val itemId: kotlin.String,

    /* The status of this item */
    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "listingInput")
    val listingInput: GetListingUpdateBatchItemListingInput,

    @Json(name = "result")
    val result: GetListingUpdateBatchItemResult? = null,

    /* If an item failed to process, the error attribute will contain the error message describing the reason the item failed to process */
    @Json(name = "error")
    val error: kotlin.String? = null

) {


}

