/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The input for this item that was used when creating the batch
 *
 * @param id The id of target listing
 */


data class GetListingDeleteBatchItemListingInput (

    /* The id of target listing */
    @Json(name = "id")
    val id: kotlin.String

) {


}

