/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param batchId Stringified UUIDv4. See [RFC 4112](https://tools.ietf.org/html/rfc4122)
 * @param status The status of this batch
 * @param completedAt When this batch fully completed. Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z
 * @param createdAt When this batch was created. Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z
 * @param updatedAt When this batch was last updated. Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z
 * @param totalItems Total number of items in this batch
 * @param itemStatuses The number of items in this batch grouped by their statuses. This is a short-hand way to quickly introspect how many items are still enqued, how many succeeded or how many failed in a batch.
 */


data class GetListingCreateBatchResponse (

    /* Stringified UUIDv4. See [RFC 4112](https://tools.ietf.org/html/rfc4122) */
    @Json(name = "batchId")
    val batchId: kotlin.String,

    /* The status of this batch */
    @Json(name = "status")
    val status: kotlin.String,

    /* When this batch fully completed. Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z */
    @Json(name = "completedAt")
    val completedAt: kotlin.String?,

    /* When this batch was created. Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z */
    @Json(name = "createdAt")
    val createdAt: kotlin.String,

    /* When this batch was last updated. Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z */
    @Json(name = "updatedAt")
    val updatedAt: kotlin.String,

    /* Total number of items in this batch */
    @Json(name = "totalItems")
    val totalItems: kotlin.Double,

    /* The number of items in this batch grouped by their statuses. This is a short-hand way to quickly introspect how many items are still enqued, how many succeeded or how many failed in a batch. */
    @Json(name = "itemStatuses")
    val itemStatuses: kotlin.collections.Map<kotlin.String, kotlin.Double>

) {


}

