/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param batchId Unique Batch ID
 * @param status The status of the batch
 * @param completedAt When this batch was completed in UTC.  Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z
 * @param createdAt When this batch was created in UTC.  Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z
 * @param updatedAt When this batch was updated in UTC.  Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z
 * @param totalItems Total number of items in this batch
 * @param itemStatuses The number of items in this batch grouped by their statuses. This is a short-hand way to quickly introspect how many items are still enqued, how many succeeded or how many failed in a batch.
 */


data class GetListingDeleteBatchResponse (

    /* Unique Batch ID */
    @Json(name = "batchId")
    val batchId: kotlin.String,

    /* The status of the batch */
    @Json(name = "status")
    val status: kotlin.String,

    /* When this batch was completed in UTC.  Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z */
    @Json(name = "completedAt")
    val completedAt: kotlin.String?,

    /* When this batch was created in UTC.  Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z */
    @Json(name = "createdAt")
    val createdAt: kotlin.String,

    /* When this batch was updated in UTC.  Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z */
    @Json(name = "updatedAt")
    val updatedAt: kotlin.String,

    /* Total number of items in this batch */
    @Json(name = "totalItems")
    val totalItems: kotlin.Double,

    /* The number of items in this batch grouped by their statuses. This is a short-hand way to quickly introspect how many items are still enqued, how many succeeded or how many failed in a batch. */
    @Json(name = "itemStatuses")
    val itemStatuses: kotlin.collections.Map<kotlin.String, kotlin.Double>

) {


}

