/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * If an item was successfully processed, the result object will contain the following:
 *
 * @param askId The unique askId of this listing.
 * @param listingId The unique listingId of this listing. This is a new ID being introduced that is analogous to askId
 */


data class GetListingDeleteBatchItemResult (

    /* The unique askId of this listing. */
    @Json(name = "askId")
    val askId: kotlin.String?,

    /* The unique listingId of this listing. This is a new ID being introduced that is analogous to askId */
    @Json(name = "listingId")
    val listingId: kotlin.String?

) {


}

