/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The input for this item that was used when creating the batch
 *
 * @param active Whether the listing is active or not
 * @param listingId The ID of the listing
 * @param currencyCode The currency code for this listing<br><br>Available values: \"AUD\", \"CAD\", \"CHF\", \"EUR\", \"GBP\", \"HKD\", \"JPY\", \"KRW\", \"MXN\", \"NZD\", \"SGD\", \"USD\"
 * @param expiresAt When this listing expires in UTC
 * @param amount The amount this listing is listed for
 */


data class GetListingUpdateBatchItemListingInput (

    /* Whether the listing is active or not */
    @Json(name = "active")
    val active: kotlin.Boolean?,

    /* The ID of the listing */
    @Json(name = "listingId")
    val listingId: kotlin.String,

    /* The currency code for this listing<br><br>Available values: \"AUD\", \"CAD\", \"CHF\", \"EUR\", \"GBP\", \"HKD\", \"JPY\", \"KRW\", \"MXN\", \"NZD\", \"SGD\", \"USD\" */
    @Json(name = "currencyCode")
    val currencyCode: kotlin.String? = null,

    /* When this listing expires in UTC */
    @Json(name = "expiresAt")
    val expiresAt: kotlin.String? = null,

    /* The amount this listing is listed for */
    @Json(name = "amount")
    val amount: kotlin.String? = null

) {


}

