/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: AUTHFAILED,DIDNOTSHIP,CANCELED,COMPLETED,RETURNED
 */

@JsonClass(generateAdapter = false)
enum class HistoricalOrderStatus(val value: kotlin.String) {

    @Json(name = "AUTHFAILED")
    AUTHFAILED("AUTHFAILED"),

    @Json(name = "DIDNOTSHIP")
    DIDNOTSHIP("DIDNOTSHIP"),

    @Json(name = "CANCELED")
    CANCELED("CANCELED"),

    @Json(name = "COMPLETED")
    COMPLETED("COMPLETED"),

    @Json(name = "RETURNED")
    RETURNED("RETURNED");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is HistoricalOrderStatus) "$data" else null

        /**
         * Returns a valid [HistoricalOrderStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): HistoricalOrderStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

