/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param brand The brand of the product.
 * @param title A string that uniquely identifies the name of the product.
 * @param variantId Unique identifier for the product variant.
 */


data class IngestionItemResult (

    /* The brand of the product. */
    @Json(name = "brand")
    val brand: kotlin.String,

    /* A string that uniquely identifies the name of the product. */
    @Json(name = "title")
    val title: kotlin.String,

    /* Unique identifier for the product variant. */
    @Json(name = "variantId")
    val variantId: kotlin.String

) {


}

