/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ingestionId Unique ID used to return the status of an ingestion job.
 */


data class IngestionControllerResponse (

    /* Unique ID used to return the status of an ingestion job. */
    @Json(name = "ingestionId")
    val ingestionId: kotlin.String

) {


}

