/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param productId Unique ID for this product
 * @param productName The name of the product
 * @param styleId The style id of the product
 */


data class ListingResponseProduct (

    /* Unique ID for this product */
    @Json(name = "productId")
    val productId: kotlin.String,

    /* The name of the product */
    @Json(name = "productName")
    val productName: kotlin.String?,

    /* The style id of the product */
    @Json(name = "styleId")
    val styleId: kotlin.String?

) {


}

