/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import com.cereal.stockx.api.model.OrderStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The current status of the order.
 *
 */


class ListOrdersStatus (

) {


}

