/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import com.cereal.stockx.api.model.DiffRecursivePartialListingChangeableFields
import com.cereal.stockx.api.model.OperationInitiatedBy
import com.cereal.stockx.api.model.OperationStatus
import com.cereal.stockx.api.model.OperationType
import com.cereal.stockx.api.model.SupportedOperationInitiatedVia

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param operationId Unique ID for this operation
 * @param operationType 
 * @param operationStatus 
 * @param operationInitiatedBy 
 * @param operationInitiatedVia 
 * @param operationCreatedAt When the operation was created in UTC. Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z
 * @param operationUpdatedAt Time of the last update in UTC. Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z
 * @param changes 
 * @param error Operation error
 */


data class ListingResponseOperation (

    /* Unique ID for this operation */
    @Json(name = "operationId")
    val operationId: kotlin.String,

    @Json(name = "operationType")
    val operationType: OperationType,

    @Json(name = "operationStatus")
    val operationStatus: OperationStatus,

    @Json(name = "operationInitiatedBy")
    val operationInitiatedBy: OperationInitiatedBy,

    @Json(name = "operationInitiatedVia")
    val operationInitiatedVia: SupportedOperationInitiatedVia,

    /* When the operation was created in UTC. Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z */
    @Json(name = "operationCreatedAt")
    val operationCreatedAt: kotlin.String,

    /* Time of the last update in UTC. Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z */
    @Json(name = "operationUpdatedAt")
    val operationUpdatedAt: kotlin.String,

    @Json(name = "changes")
    val changes: DiffRecursivePartialListingChangeableFields,

    /* Operation error */
    @Json(name = "error")
    val error: kotlin.String? = null

) {


}

