/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param batchId ID of the associated batch
 * @param taskId Id of the associated task
 */


data class ListingsResponseBatch (

    /* ID of the associated batch */
    @Json(name = "batchId")
    val batchId: kotlin.String? = null,

    /* Id of the associated task */
    @Json(name = "taskId")
    val taskId: kotlin.String? = null

) {


}

