/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import com.cereal.stockx.api.model.AuthenticationDetails
import com.cereal.stockx.api.model.ListingResponseAsk
import com.cereal.stockx.api.model.ListingResponseOperation
import com.cereal.stockx.api.model.ListingResponseOrder
import com.cereal.stockx.api.model.ListingResponseProduct
import com.cereal.stockx.api.model.ListingResponseVariant
import com.cereal.stockx.api.model.ListingsResponseBatch
import com.cereal.stockx.api.model.ManifestDataResponse
import com.cereal.stockx.api.model.Payout

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param listingId Unique ID for this listing
 * @param status The current status of the listing<br><br>Available values: \"INACTIVE\", \"ACTIVE\", \"DELETED\", \"CANCELED\", \"MATCHED\", \"COMPLETED\"
 * @param amount The amount this product is being listed for
 * @param currencyCode The currency code. If not provided, it will default to USD.  Only valid currencies supported on stockx.com are supported via API.<br><br>Available values: \"AUD\", \"CAD\", \"CHF\", \"EUR\", \"GBP\", \"HKD\", \"JPY\", \"KRW\", \"MXN\", \"NZD\", \"SGD\", \"USD\"
 * @param inventoryType A representation of the type of inventory being listed
 * @param createdAt When the listing was created in UTC. Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z
 * @param updatedAt When this listing was last updated in UTC.  Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z
 * @param batch Information about the batch this listing is part of, if this listing was touched with the batch APIs
 * @param ask An object with ask details
 * @param order An object containing the order details
 * @param product An object containing the product details.
 * @param variant Details about the particular product variant
 * @param authenticationDetails Details about authentication status and failure notes
 * @param payout The payout object that contains the payout details and any adjustments like selling fees, shipping fees, taxes, etc.
 * @param lastOperation An object containing the the details of the operation.
 * @param initiatedShipments Details about manifests associated with the listing
 */


data class ListingResponse (

    /* Unique ID for this listing */
    @Json(name = "listingId")
    val listingId: kotlin.String,

    /* The current status of the listing<br><br>Available values: \"INACTIVE\", \"ACTIVE\", \"DELETED\", \"CANCELED\", \"MATCHED\", \"COMPLETED\" */
    @Json(name = "status")
    val status: kotlin.String,

    /* The amount this product is being listed for */
    @Json(name = "amount")
    val amount: kotlin.String?,

    /* The currency code. If not provided, it will default to USD.  Only valid currencies supported on stockx.com are supported via API.<br><br>Available values: \"AUD\", \"CAD\", \"CHF\", \"EUR\", \"GBP\", \"HKD\", \"JPY\", \"KRW\", \"MXN\", \"NZD\", \"SGD\", \"USD\" */
    @Json(name = "currencyCode")
    val currencyCode: kotlin.String?,

    /* A representation of the type of inventory being listed */
    @Json(name = "inventoryType")
    val inventoryType: kotlin.String?,

    /* When the listing was created in UTC. Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z */
    @Json(name = "createdAt")
    val createdAt: kotlin.String,

    /* When this listing was last updated in UTC.  Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z */
    @Json(name = "updatedAt")
    val updatedAt: kotlin.String,

    /* Information about the batch this listing is part of, if this listing was touched with the batch APIs */
    @Json(name = "batch")
    val batch: ListingsResponseBatch?,

    /* An object with ask details */
    @Json(name = "ask")
    val ask: ListingResponseAsk?,

    /* An object containing the order details */
    @Json(name = "order")
    val order: ListingResponseOrder?,

    /* An object containing the product details. */
    @Json(name = "product")
    val product: ListingResponseProduct?,

    /* Details about the particular product variant */
    @Json(name = "variant")
    val variant: ListingResponseVariant?,

    /* Details about authentication status and failure notes */
    @Json(name = "authenticationDetails")
    val authenticationDetails: AuthenticationDetails?,

    /* The payout object that contains the payout details and any adjustments like selling fees, shipping fees, taxes, etc. */
    @Json(name = "payout")
    val payout: Payout?,

    /* An object containing the the details of the operation. */
    @Json(name = "lastOperation")
    val lastOperation: ListingResponseOperation?,

    /* Details about manifests associated with the listing */
    @Json(name = "initiatedShipments")
    val initiatedShipments: ManifestDataResponse?

) {


}

