/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param orderNumber The order number. Standard example: 323314425-323214184. Flex example: 02-L0QT6MRVSG
 * @param orderCreatedAt When the order was created
 * @param orderStatus The status of the given order
 */


data class ListingResponseOrder (

    /* The order number. Standard example: 323314425-323214184. Flex example: 02-L0QT6MRVSG */
    @Json(name = "orderNumber")
    val orderNumber: kotlin.String?,

    /* When the order was created */
    @Json(name = "orderCreatedAt")
    val orderCreatedAt: kotlin.String?,

    /* The status of the given order */
    @Json(name = "orderStatus")
    val orderStatus: kotlin.String?

) {


}

