/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Product information
 *
 * @param productId StockX product ID
 * @param productName Name of the product
 * @param styleId Style id of the product
 */


data class OrderProduct (

    /* StockX product ID */
    @Json(name = "productId")
    val productId: kotlin.String,

    /* Name of the product */
    @Json(name = "productName")
    val productName: kotlin.String?,

    /* Style id of the product */
    @Json(name = "styleId")
    val styleId: kotlin.String?

) {


}

