/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import com.cereal.stockx.api.model.ActiveOrderStatus
import com.cereal.stockx.api.model.HistoricalOrderStatus
import com.cereal.stockx.api.model.UnknownStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Status for the current order
 *
 */


class OrderStatus (

) {


}

