/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name The display name for the size conversion
 * @param type The type of the size conversion
 */


data class ProductSizeConversion (

    /* The display name for the size conversion */
    @Json(name = "name")
    val name: kotlin.String?,

    /* The type of the size conversion */
    @Json(name = "type")
    val type: kotlin.String?

) {


}

