/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import com.cereal.stockx.api.model.ProductSizeConversion

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Size chart information for the product
 *
 * @param availableConversions The available size chart conversions this product has
 * @param defaultConversion The default sizing this product uses
 */


data class ProductSizeChart (

    /* The available size chart conversions this product has */
    @Json(name = "availableConversions")
    val availableConversions: kotlin.collections.List<ProductSizeConversion>,

    /* The default sizing this product uses */
    @Json(name = "defaultConversion")
    val defaultConversion: ProductSizeConversion?

) {


}

