/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: sneakers,shoes,apparel,accessories,collectibles,electronics,trading_cards
 */

@JsonClass(generateAdapter = false)
enum class PRODUCTCATEGORIES(val value: kotlin.String) {

    @Json(name = "sneakers")
    sneakers("sneakers"),

    @Json(name = "shoes")
    shoes("shoes"),

    @Json(name = "apparel")
    apparel("apparel"),

    @Json(name = "accessories")
    accessories("accessories"),

    @Json(name = "collectibles")
    collectibles("collectibles"),

    @Json(name = "electronics")
    electronics("electronics"),

    @Json(name = "trading cards")
    trading_cards("trading cards");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PRODUCTCATEGORIES) "$data" else null

        /**
         * Returns a valid [PRODUCTCATEGORIES] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PRODUCTCATEGORIES? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

