/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import com.cereal.stockx.api.model.ProductVariantDetailsSizeChart

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Variant information
 *
 * @param productId Unique identifier for a product
 * @param variantId Unique identifier for a products variant
 * @param variantName SKU of the variant
 * @param variantValue Variant's value
 * @param sizeChart 
 */


data class ProductVariant (

    /* Unique identifier for a product */
    @Json(name = "productId")
    val productId: kotlin.String,

    /* Unique identifier for a products variant */
    @Json(name = "variantId")
    val variantId: kotlin.String,

    /* SKU of the variant */
    @Json(name = "variantName")
    val variantName: kotlin.String,

    /* Variant's value */
    @Json(name = "variantValue")
    val variantValue: kotlin.String?,

    @Json(name = "sizeChart")
    val sizeChart: ProductVariantDetailsSizeChart

) {


}

