/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import com.cereal.stockx.api.model.PRODUCTCODENAME

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param code Unique code that identifies the product.
 * @param name 
 */


data class ProductCode (

    /* Unique code that identifies the product. */
    @Json(name = "code")
    val code: kotlin.String,

    @Json(name = "name")
    val name: PRODUCTCODENAME

) {


}

