/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import com.cereal.stockx.api.model.VariantSizeConversion

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Size chart related information for this variant
 *
 * @param availableConversions The available size conversions for this variant
 * @param defaultConversion The default sizing information for this variant
 */


data class ProductVariantDetailsSizeChart (

    /* The available size conversions for this variant */
    @Json(name = "availableConversions")
    val availableConversions: kotlin.collections.List<VariantSizeConversion>,

    /* The default sizing information for this variant */
    @Json(name = "defaultConversion")
    val defaultConversion: VariantSizeConversion?

) {


}

