/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import com.cereal.stockx.api.model.ProductProductAttributes
import com.cereal.stockx.api.model.ProductSizeChart

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Product information
 *
 * @param productId Unique identifier for a product
 * @param urlKey The product name
 * @param styleId ID of prduct style
 * @param productType The type of product categories that are available on StockX
 * @param title A string that uniquely identifies the product name.
 * @param brand Brand of the product
 * @param productAttributes 
 * @param sizeChart 
 */


data class Product (

    /* Unique identifier for a product */
    @Json(name = "productId")
    val productId: kotlin.String,

    /* The product name */
    @Json(name = "urlKey")
    val urlKey: kotlin.String,

    /* ID of prduct style */
    @Json(name = "styleId")
    val styleId: kotlin.String?,

    /* The type of product categories that are available on StockX */
    @Json(name = "productType")
    val productType: kotlin.String,

    /* A string that uniquely identifies the product name. */
    @Json(name = "title")
    val title: kotlin.String?,

    /* Brand of the product */
    @Json(name = "brand")
    val brand: kotlin.String?,

    @Json(name = "productAttributes")
    val productAttributes: ProductProductAttributes,

    @Json(name = "sizeChart")
    val sizeChart: ProductSizeChart? = null

) {


}

