/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import com.cereal.stockx.api.model.HttpStatusCodeLiteral

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param statusCode 
 * @param message The error message
 */


data class PublicApiError (

    @Json(name = "statusCode")
    val statusCode: HttpStatusCodeLiteral,

    /* The error message */
    @Json(name = "message")
    val message: kotlin.String

) {


}

