/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import com.cereal.stockx.api.model.Product

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param count Total number of items present
 * @param pageSize Total number of items in the current page
 * @param pageNumber Requested page number. Starts at 1.
 * @param hasNextPage Returns true if there are elements in the next page.
 * @param products List of products that matched the search term
 */


data class Search (

    /* Total number of items present */
    @Json(name = "count")
    val count: kotlin.Double,

    /* Total number of items in the current page */
    @Json(name = "pageSize")
    val pageSize: kotlin.Double,

    /* Requested page number. Starts at 1. */
    @Json(name = "pageNumber")
    val pageNumber: kotlin.Double,

    /* Returns true if there are elements in the next page. */
    @Json(name = "hasNextPage")
    val hasNextPage: kotlin.Boolean,

    /* List of products that matched the search term */
    @Json(name = "products")
    val products: kotlin.collections.List<Product>

) {


}

