/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param shipByDate Date that the order should be shipped by.
 * @param trackingNumber The shipments tracking number
 * @param trackingUrl The URL to the carriers web page.
 * @param carrierCode The carrier code for the shipment provider.
 * @param shippingLabelUrl The URL of the shipping label
 * @param shippingDocumentUrl The URL of the StockX shipping document.
 */


data class Shipment (

    /* Date that the order should be shipped by. */
    @Json(name = "shipByDate")
    val shipByDate: kotlin.String?,

    /* The shipments tracking number */
    @Json(name = "trackingNumber")
    val trackingNumber: kotlin.String?,

    /* The URL to the carriers web page. */
    @Json(name = "trackingUrl")
    val trackingUrl: kotlin.String?,

    /* The carrier code for the shipment provider. */
    @Json(name = "carrierCode")
    val carrierCode: kotlin.String?,

    /* The URL of the shipping label */
    @Json(name = "shippingLabelUrl")
    val shippingLabelUrl: kotlin.String?,

    /* The URL of the StockX shipping document. */
    @Json(name = "shippingDocumentUrl")
    val shippingDocumentUrl: kotlin.String?

) {


}

