/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: IOS,ANDROID,WEB,STOCKXMinusPRO,SCOUT,SHOPIFY,PUBLICMinusAPI,INTERNALMinusSYSTEM
 */

@JsonClass(generateAdapter = false)
enum class SupportedOperationInitiatedVia(val value: kotlin.String) {

    @Json(name = "IOS")
    IOS("IOS"),

    @Json(name = "ANDROID")
    ANDROID("ANDROID"),

    @Json(name = "WEB")
    WEB("WEB"),

    @Json(name = "STOCKX-PRO")
    STOCKXMinusPRO("STOCKX-PRO"),

    @Json(name = "SCOUT")
    SCOUT("SCOUT"),

    @Json(name = "SHOPIFY")
    SHOPIFY("SHOPIFY"),

    @Json(name = "PUBLIC-API")
    PUBLICMinusAPI("PUBLIC-API"),

    @Json(name = "INTERNAL-SYSTEM")
    INTERNALMinusSYSTEM("INTERNAL-SYSTEM");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SupportedOperationInitiatedVia) "$data" else null

        /**
         * Returns a valid [SupportedOperationInitiatedVia] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SupportedOperationInitiatedVia? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

