/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param amount The amount that will appear on stockx.com The amount this product is being listed for
 * @param currencyCode Currency in which the ask is placed<br><br>Available values: \"AUD\", \"CAD\", \"CHF\", \"EUR\", \"GBP\", \"HKD\", \"JPY\", \"KRW\", \"MXN\", \"NZD\", \"SGD\", \"USD\" The currency code this product is being listed in. If not provided, it will default to USD.  Only valid currencies supported on stockx.com are supported via API.<br><br>Available values: \"AUD\", \"CAD\", \"CHF\", \"EUR\", \"GBP\", \"HKD\", \"JPY\", \"KRW\", \"MXN\", \"NZD\", \"SGD\", \"USD\"
 * @param expiresAt When the ask expires UTC timestamp representing when this listing should auto-expire.  If not provided, it will default to 365 days from today. Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z
 */


data class UpdateListingInput (

    /* The amount that will appear on stockx.com The amount this product is being listed for */
    @Json(name = "amount")
    val amount: kotlin.String? = null,

    /* Currency in which the ask is placed<br><br>Available values: \"AUD\", \"CAD\", \"CHF\", \"EUR\", \"GBP\", \"HKD\", \"JPY\", \"KRW\", \"MXN\", \"NZD\", \"SGD\", \"USD\" The currency code this product is being listed in. If not provided, it will default to USD.  Only valid currencies supported on stockx.com are supported via API.<br><br>Available values: \"AUD\", \"CAD\", \"CHF\", \"EUR\", \"GBP\", \"HKD\", \"JPY\", \"KRW\", \"MXN\", \"NZD\", \"SGD\", \"USD\" */
    @Json(name = "currencyCode")
    val currencyCode: kotlin.String? = null,

    /* When the ask expires UTC timestamp representing when this listing should auto-expire.  If not provided, it will default to 365 days from today. Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z */
    @Json(name = "expiresAt")
    val expiresAt: kotlin.String? = null

) {


}

