/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param listingId Unique listing ID that needs to be updated
 * @param amount The amount this Listing is updated to
 * @param expiresAt UTC timestamp representing the Listing expiry date that is being updated to
 * @param currencyCode The currency this Listing is updated to<br><br>Available values: \"AUD\", \"CAD\", \"CHF\", \"EUR\", \"GBP\", \"HKD\", \"JPY\", \"KRW\", \"MXN\", \"NZD\", \"SGD\", \"USD\"
 * @param active Flag used to indicate that the listing should be active or not
 */


data class UpdateBatchListingRequestItem (

    /* Unique listing ID that needs to be updated */
    @Json(name = "listingId")
    val listingId: kotlin.String,

    /* The amount this Listing is updated to */
    @Json(name = "amount")
    val amount: kotlin.String? = null,

    /* UTC timestamp representing the Listing expiry date that is being updated to */
    @Json(name = "expiresAt")
    val expiresAt: kotlin.String? = null,

    /* The currency this Listing is updated to<br><br>Available values: \"AUD\", \"CAD\", \"CHF\", \"EUR\", \"GBP\", \"HKD\", \"JPY\", \"KRW\", \"MXN\", \"NZD\", \"SGD\", \"USD\" */
    @Json(name = "currencyCode")
    val currencyCode: kotlin.String? = null,

    /* Flag used to indicate that the listing should be active or not */
    @Json(name = "active")
    val active: kotlin.Boolean? = null

) {


}

