/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param propertySize The size of this size conversion
 * @param type The type of the size conversion/chart
 */


data class VariantSizeConversion (

    /* The size of this size conversion */
    @Json(name = "size")
    val propertySize: kotlin.String?,

    /* The type of the size conversion/chart */
    @Json(name = "type")
    val type: kotlin.String?

) {


}

