/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Variant information
 *
 * @param variantId Unique identifier for a products variant
 * @param variantName Unique readable name of the products variant
 * @param variantValue The value of the variant. For example, in the sneakers case, this could be 10 or in the trading cards case, this could be PSA 10, etc.
 */


data class Variant (

    /* Unique identifier for a products variant */
    @Json(name = "variantId")
    val variantId: kotlin.String,

    /* Unique readable name of the products variant */
    @Json(name = "variantName")
    val variantName: kotlin.String,

    /* The value of the variant. For example, in the sneakers case, this could be 10 or in the trading cards case, this could be PSA 10, etc. */
    @Json(name = "variantValue")
    val variantValue: kotlin.String?

) {


}

