/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.BatchApi
import com.cereal.stockx.api.model.BatchCreateListingInput
import com.cereal.stockx.api.model.BatchCreateListingResponse
import com.cereal.stockx.api.model.BatchDeleteListingInput
import com.cereal.stockx.api.model.BatchDeleteListingResponse
import com.cereal.stockx.api.model.BatchUpdateListingInput
import com.cereal.stockx.api.model.BatchUpdateListingResponse
import com.cereal.stockx.api.model.GetListingCreateBatchItemsResponse
import com.cereal.stockx.api.model.GetListingCreateBatchResponse
import com.cereal.stockx.api.model.GetListingDeleteBatchItemsResponse
import com.cereal.stockx.api.model.GetListingDeleteBatchResponse
import com.cereal.stockx.api.model.GetListingUpdateBatchItemsResponse
import com.cereal.stockx.api.model.GetListingUpdateBatchResponse
import com.cereal.stockx.api.model.PublicApiError

class BatchApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BatchApi
        //val apiInstance = BatchApi()

        // to test createListings
        should("test createListings") {
            // uncomment below to test createListings
            //val batchCreateListingInput : BatchCreateListingInput =  // BatchCreateListingInput | 
            //val result : BatchCreateListingResponse = apiInstance.createListings(batchCreateListingInput)
            //result shouldBe ("TODO")
        }

        // to test deleteListings
        should("test deleteListings") {
            // uncomment below to test deleteListings
            //val batchDeleteListingInput : BatchDeleteListingInput =  // BatchDeleteListingInput | 
            //val result : BatchDeleteListingResponse = apiInstance.deleteListings(batchDeleteListingInput)
            //result shouldBe ("TODO")
        }

        // to test getListingCreateBatch
        should("test getListingCreateBatch") {
            // uncomment below to test getListingCreateBatch
            //val batchId : kotlin.String = batchId_example // kotlin.String | Unique Batch ID
            //val result : GetListingCreateBatchResponse = apiInstance.getListingCreateBatch(batchId)
            //result shouldBe ("TODO")
        }

        // to test getListingCreateBatchItems
        should("test getListingCreateBatchItems") {
            // uncomment below to test getListingCreateBatchItems
            //val batchId : kotlin.String = batchId_example // kotlin.String | The ID of batch
            //val status : kotlin.String = COMPLETED // kotlin.String | Status of listing
            //val result : GetListingCreateBatchItemsResponse = apiInstance.getListingCreateBatchItems(batchId, status)
            //result shouldBe ("TODO")
        }

        // to test getListingDeleteBatch
        should("test getListingDeleteBatch") {
            // uncomment below to test getListingDeleteBatch
            //val batchId : kotlin.String = batchId_example // kotlin.String | Unique Batch ID
            //val result : GetListingDeleteBatchResponse = apiInstance.getListingDeleteBatch(batchId)
            //result shouldBe ("TODO")
        }

        // to test getListingDeleteBatchItems
        should("test getListingDeleteBatchItems") {
            // uncomment below to test getListingDeleteBatchItems
            //val batchId : kotlin.String = batchId_example // kotlin.String | Unique Batch ID
            //val status : kotlin.String = COMPLETED // kotlin.String | 
            //val result : GetListingDeleteBatchItemsResponse = apiInstance.getListingDeleteBatchItems(batchId, status)
            //result shouldBe ("TODO")
        }

        // to test getListingUpdateBatch
        should("test getListingUpdateBatch") {
            // uncomment below to test getListingUpdateBatch
            //val batchId : kotlin.String = batchId_example // kotlin.String | Unique Batch ID
            //val result : GetListingUpdateBatchResponse = apiInstance.getListingUpdateBatch(batchId)
            //result shouldBe ("TODO")
        }

        // to test getListingUpdateBatchItems
        should("test getListingUpdateBatchItems") {
            // uncomment below to test getListingUpdateBatchItems
            //val batchId : kotlin.String = batchId_example // kotlin.String | Unique Batch ID
            //val status : kotlin.String = COMPLETED // kotlin.String | Status of listing
            //val result : GetListingUpdateBatchItemsResponse = apiInstance.getListingUpdateBatchItems(batchId, status)
            //result shouldBe ("TODO")
        }

        // to test updateListings
        should("test updateListings") {
            // uncomment below to test updateListings
            //val batchUpdateListingInput : BatchUpdateListingInput =  // BatchUpdateListingInput | 
            //val result : BatchUpdateListingResponse = apiInstance.updateListings(batchUpdateListingInput)
            //result shouldBe ("TODO")
        }

    }
}
