/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.Adjustment

class AdjustmentTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Adjustment
        //val modelInstance = Adjustment()

        // to test the property `adjustmentType` - The type of adjustment made
        should("test adjustmentType") {
            // uncomment below to test the property
            //modelInstance.adjustmentType shouldBe ("TODO")
        }

        // to test the property `amount` - The amount of the adjustment
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `percentage` - The percentage of the adjustment
        should("test percentage") {
            // uncomment below to test the property
            //modelInstance.percentage shouldBe ("TODO")
        }

    }
}
