/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.CatalogIngestionInput
import com.cereal.stockx.api.model.CatalogIngestionInputItemsInner

class CatalogIngestionInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CatalogIngestionInput
        //val modelInstance = CatalogIngestionInput()

        // to test the property `items` - An array of items associated with the ingestion job.
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

    }
}
