/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.DeleteBatchListingRequestItem

class DeleteBatchListingRequestItemTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeleteBatchListingRequestItem
        //val modelInstance = DeleteBatchListingRequestItem()

        // to test the property `listingId` - Unique listing ID that needs to be deleted
        should("test listingId") {
            // uncomment below to test the property
            //modelInstance.listingId shouldBe ("TODO")
        }

    }
}
