/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.DiffRecursivePartialListingChangeableFields

class DiffRecursivePartialListingChangeableFieldsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DiffRecursivePartialListingChangeableFields
        //val modelInstance = DiffRecursivePartialListingChangeableFields()

        // to test the property `additions` - The additions of current listing
        should("test additions") {
            // uncomment below to test the property
            //modelInstance.additions shouldBe ("TODO")
        }

        // to test the property `updates` - The updates of current listing
        should("test updates") {
            // uncomment below to test the property
            //modelInstance.updates shouldBe ("TODO")
        }

        // to test the property `removals` - The removals of current listing
        should("test removals") {
            // uncomment below to test the property
            //modelInstance.removals shouldBe ("TODO")
        }

    }
}
