/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.GetIngestionItemsReponse
import com.cereal.stockx.api.model.GetIngestionItem

class GetIngestionItemsReponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetIngestionItemsReponse
        //val modelInstance = GetIngestionItemsReponse()

        // to test the property `items`
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

    }
}
