/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.GetListingDeleteBatchItemListingInput

class GetListingDeleteBatchItemListingInputTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetListingDeleteBatchItemListingInput
        //val modelInstance = GetListingDeleteBatchItemListingInput()

        // to test the property `id` - The id of target listing
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

    }
}
