/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.GetListingUpdateBatchItemsResponse
import com.cereal.stockx.api.model.GetListingUpdateBatchItem

class GetListingUpdateBatchItemsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetListingUpdateBatchItemsResponse
        //val modelInstance = GetListingUpdateBatchItemsResponse()

        // to test the property `items` - An array of items associated with the listing
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

    }
}
