/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.GetListingDeleteBatchItemResult

class GetListingDeleteBatchItemResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetListingDeleteBatchItemResult
        //val modelInstance = GetListingDeleteBatchItemResult()

        // to test the property `askId` - The unique askId of this listing.
        should("test askId") {
            // uncomment below to test the property
            //modelInstance.askId shouldBe ("TODO")
        }

        // to test the property `listingId` - The unique listingId of this listing. This is a new ID being introduced that is analogous to askId
        should("test listingId") {
            // uncomment below to test the property
            //modelInstance.listingId shouldBe ("TODO")
        }

    }
}
