/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.GetListingUpdateBatchItem
import com.cereal.stockx.api.model.GetListingUpdateBatchItemListingInput
import com.cereal.stockx.api.model.GetListingUpdateBatchItemResult

class GetListingUpdateBatchItemTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetListingUpdateBatchItem
        //val modelInstance = GetListingUpdateBatchItem()

        // to test the property `itemId` - Unique Item ID
        should("test itemId") {
            // uncomment below to test the property
            //modelInstance.itemId shouldBe ("TODO")
        }

        // to test the property `status` - The status of this item
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `listingInput`
        should("test listingInput") {
            // uncomment below to test the property
            //modelInstance.listingInput shouldBe ("TODO")
        }

        // to test the property `result`
        should("test result") {
            // uncomment below to test the property
            //modelInstance.result shouldBe ("TODO")
        }

        // to test the property `error` - If an item failed to process, the error attribute will contain the error message describing the reason the item failed to process
        should("test error") {
            // uncomment below to test the property
            //modelInstance.error shouldBe ("TODO")
        }

    }
}
