/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.IngestionControllerResponse

class IngestionControllerResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of IngestionControllerResponse
        //val modelInstance = IngestionControllerResponse()

        // to test the property `ingestionId` - Unique ID used to return the status of an ingestion job.
        should("test ingestionId") {
            // uncomment below to test the property
            //modelInstance.ingestionId shouldBe ("TODO")
        }

    }
}
