/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.ListingResponseOrder

class ListingResponseOrderTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListingResponseOrder
        //val modelInstance = ListingResponseOrder()

        // to test the property `orderNumber` - The order number. Standard example: 323314425-323214184. Flex example: 02-L0QT6MRVSG
        should("test orderNumber") {
            // uncomment below to test the property
            //modelInstance.orderNumber shouldBe ("TODO")
        }

        // to test the property `orderCreatedAt` - When the order was created
        should("test orderCreatedAt") {
            // uncomment below to test the property
            //modelInstance.orderCreatedAt shouldBe ("TODO")
        }

        // to test the property `orderStatus` - The status of the given order
        should("test orderStatus") {
            // uncomment below to test the property
            //modelInstance.orderStatus shouldBe ("TODO")
        }

    }
}
