/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.ListingResponseOperation
import com.cereal.stockx.api.model.DiffRecursivePartialListingChangeableFields
import com.cereal.stockx.api.model.OperationInitiatedBy
import com.cereal.stockx.api.model.OperationStatus
import com.cereal.stockx.api.model.OperationType
import com.cereal.stockx.api.model.SupportedOperationInitiatedVia

class ListingResponseOperationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListingResponseOperation
        //val modelInstance = ListingResponseOperation()

        // to test the property `operationId` - Unique ID for this operation
        should("test operationId") {
            // uncomment below to test the property
            //modelInstance.operationId shouldBe ("TODO")
        }

        // to test the property `operationType`
        should("test operationType") {
            // uncomment below to test the property
            //modelInstance.operationType shouldBe ("TODO")
        }

        // to test the property `operationStatus`
        should("test operationStatus") {
            // uncomment below to test the property
            //modelInstance.operationStatus shouldBe ("TODO")
        }

        // to test the property `operationInitiatedBy`
        should("test operationInitiatedBy") {
            // uncomment below to test the property
            //modelInstance.operationInitiatedBy shouldBe ("TODO")
        }

        // to test the property `operationInitiatedVia`
        should("test operationInitiatedVia") {
            // uncomment below to test the property
            //modelInstance.operationInitiatedVia shouldBe ("TODO")
        }

        // to test the property `operationCreatedAt` - When the operation was created in UTC. Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z
        should("test operationCreatedAt") {
            // uncomment below to test the property
            //modelInstance.operationCreatedAt shouldBe ("TODO")
        }

        // to test the property `operationUpdatedAt` - Time of the last update in UTC. Represented as ISO 8601 format like 2021-11-09T12:44:31.000Z
        should("test operationUpdatedAt") {
            // uncomment below to test the property
            //modelInstance.operationUpdatedAt shouldBe ("TODO")
        }

        // to test the property `changes`
        should("test changes") {
            // uncomment below to test the property
            //modelInstance.changes shouldBe ("TODO")
        }

        // to test the property `error` - Operation error
        should("test error") {
            // uncomment below to test the property
            //modelInstance.error shouldBe ("TODO")
        }

    }
}
