/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.Listings
import com.cereal.stockx.api.model.ListListings

class ListingsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Listings
        //val modelInstance = Listings()

        // to test the property `count` - Total number of items present
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

        // to test the property `pageSize` - Total number of items in the current page
        should("test pageSize") {
            // uncomment below to test the property
            //modelInstance.pageSize shouldBe ("TODO")
        }

        // to test the property `pageNumber` - Requested page number. Starts at 1.
        should("test pageNumber") {
            // uncomment below to test the property
            //modelInstance.pageNumber shouldBe ("TODO")
        }

        // to test the property `hasNextPage` - Returns true if there are elements in the next page.
        should("test hasNextPage") {
            // uncomment below to test the property
            //modelInstance.hasNextPage shouldBe ("TODO")
        }

        // to test the property `listings` - List of listings
        should("test listings") {
            // uncomment below to test the property
            //modelInstance.listings shouldBe ("TODO")
        }

    }
}
