/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.ListOrdersStatus
import com.cereal.stockx.api.model.OrderStatus

class ListOrdersStatusTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListOrdersStatus
        //val modelInstance = ListOrdersStatus()

    }
}
