/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.ListingResponseAsk

class ListingResponseAskTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListingResponseAsk
        //val modelInstance = ListingResponseAsk()

        // to test the property `askId` - Id of the created ask
        should("test askId") {
            // uncomment below to test the property
            //modelInstance.askId shouldBe ("TODO")
        }

        // to test the property `askCreatedAt` - When the ask was created
        should("test askCreatedAt") {
            // uncomment below to test the property
            //modelInstance.askCreatedAt shouldBe ("TODO")
        }

        // to test the property `askUpdatedAt` - When the ask was updated
        should("test askUpdatedAt") {
            // uncomment below to test the property
            //modelInstance.askUpdatedAt shouldBe ("TODO")
        }

        // to test the property `askExpiresAt` - When the ask will expire
        should("test askExpiresAt") {
            // uncomment below to test the property
            //modelInstance.askExpiresAt shouldBe ("TODO")
        }

    }
}
