/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.ListingsResponseBatch

class ListingsResponseBatchTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListingsResponseBatch
        //val modelInstance = ListingsResponseBatch()

        // to test the property `batchId` - ID of the associated batch
        should("test batchId") {
            // uncomment below to test the property
            //modelInstance.batchId shouldBe ("TODO")
        }

        // to test the property `taskId` - Id of the associated task
        should("test taskId") {
            // uncomment below to test the property
            //modelInstance.taskId shouldBe ("TODO")
        }

    }
}
