/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.ListingResponseProduct

class ListingResponseProductTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListingResponseProduct
        //val modelInstance = ListingResponseProduct()

        // to test the property `productId` - Unique ID for this product
        should("test productId") {
            // uncomment below to test the property
            //modelInstance.productId shouldBe ("TODO")
        }

        // to test the property `productName` - The name of the product
        should("test productName") {
            // uncomment below to test the property
            //modelInstance.productName shouldBe ("TODO")
        }

        // to test the property `styleId` - The style id of the product
        should("test styleId") {
            // uncomment below to test the property
            //modelInstance.styleId shouldBe ("TODO")
        }

    }
}
