/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.ManifestDataResponse
import com.cereal.stockx.api.model.ManifestDataResponseInbound

class ManifestDataResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ManifestDataResponse
        //val modelInstance = ManifestDataResponse()

        // to test the property `inbound`
        should("test inbound") {
            // uncomment below to test the property
            //modelInstance.inbound shouldBe ("TODO")
        }

    }
}
