/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.ManifestDataResponseInbound

class ManifestDataResponseInboundTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ManifestDataResponseInbound
        //val modelInstance = ManifestDataResponseInbound()

        // to test the property `displayId` - The ID associated with the shipment arriving at StockX. Note: This is the same ID generated when a Flex inbound list is created in StockX Pro.
        should("test displayId") {
            // uncomment below to test the property
            //modelInstance.displayId shouldBe ("TODO")
        }

    }
}
