/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.OperationsCursorResponse
import com.cereal.stockx.api.model.OperationApi

class OperationsCursorResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OperationsCursorResponse
        //val modelInstance = OperationsCursorResponse()

        // to test the property `nextCursor` - Used for pagination when more than 200 operations are retrieved. The nextCursor value received in response will be same for all subsequent page requests.
        should("test nextCursor") {
            // uncomment below to test the property
            //modelInstance.nextCursor shouldBe ("TODO")
        }

        // to test the property `operations` - A list of the operations requested
        should("test operations") {
            // uncomment below to test the property
            //modelInstance.operations shouldBe ("TODO")
        }

    }
}
