/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.OrderProduct

class OrderProductTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderProduct
        //val modelInstance = OrderProduct()

        // to test the property `productId` - StockX product ID
        should("test productId") {
            // uncomment below to test the property
            //modelInstance.productId shouldBe ("TODO")
        }

        // to test the property `productName` - Name of the product
        should("test productName") {
            // uncomment below to test the property
            //modelInstance.productName shouldBe ("TODO")
        }

        // to test the property `styleId` - Style id of the product
        should("test styleId") {
            // uncomment below to test the property
            //modelInstance.styleId shouldBe ("TODO")
        }

    }
}
