/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.Payout
import com.cereal.stockx.api.model.Adjustment

class PayoutTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Payout
        //val modelInstance = Payout()

        // to test the property `totalPayout` - The total amount to be paid for the sale of the product
        should("test totalPayout") {
            // uncomment below to test the property
            //modelInstance.totalPayout shouldBe ("TODO")
        }

        // to test the property `salePrice` - The amount the product was sold for
        should("test salePrice") {
            // uncomment below to test the property
            //modelInstance.salePrice shouldBe ("TODO")
        }

        // to test the property `totalAdjustments` - The sum of all adjustments made
        should("test totalAdjustments") {
            // uncomment below to test the property
            //modelInstance.totalAdjustments shouldBe ("TODO")
        }

        // to test the property `currencyCode` - The currency code this product is being listed in. If not provided, it will default to USD.  Only valid currencies supported on stockx.com are supported via API.<br><br>Available values: \"AUD\", \"CAD\", \"CHF\", \"EUR\", \"GBP\", \"HKD\", \"JPY\", \"KRW\", \"MXN\", \"NZD\", \"SGD\", \"USD\"
        should("test currencyCode") {
            // uncomment below to test the property
            //modelInstance.currencyCode shouldBe ("TODO")
        }

        // to test the property `adjustments` - The payout adjustment details if applicable
        should("test adjustments") {
            // uncomment below to test the property
            //modelInstance.adjustments shouldBe ("TODO")
        }

    }
}
