/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.ProductProductAttributes

class ProductProductAttributesTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProductProductAttributes
        //val modelInstance = ProductProductAttributes()

        // to test the property `gender` - Gender targeted product
        should("test gender") {
            // uncomment below to test the property
            //modelInstance.gender shouldBe ("TODO")
        }

        // to test the property `season` - The season the product was released
        should("test season") {
            // uncomment below to test the property
            //modelInstance.season shouldBe ("TODO")
        }

        // to test the property `releaseDate` - The date the product was released
        should("test releaseDate") {
            // uncomment below to test the property
            //modelInstance.releaseDate shouldBe ("TODO")
        }

        // to test the property `retailPrice` - The retail price of the product.
        should("test retailPrice") {
            // uncomment below to test the property
            //modelInstance.retailPrice shouldBe ("TODO")
        }

        // to test the property `colorway` - The combinations of colors in which the product is designed
        should("test colorway") {
            // uncomment below to test the property
            //modelInstance.colorway shouldBe ("TODO")
        }

        // to test the property `color` - Color of product
        should("test color") {
            // uncomment below to test the property
            //modelInstance.color shouldBe ("TODO")
        }

    }
}
