/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.ProductVariantDetailsSizeChart
import com.cereal.stockx.api.model.VariantSizeConversion

class ProductVariantDetailsSizeChartTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProductVariantDetailsSizeChart
        //val modelInstance = ProductVariantDetailsSizeChart()

        // to test the property `availableConversions` - The available size conversions for this variant
        should("test availableConversions") {
            // uncomment below to test the property
            //modelInstance.availableConversions shouldBe ("TODO")
        }

        // to test the property `defaultConversion` - The default sizing information for this variant
        should("test defaultConversion") {
            // uncomment below to test the property
            //modelInstance.defaultConversion shouldBe ("TODO")
        }

    }
}
