/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.Product
import com.cereal.stockx.api.model.ProductProductAttributes
import com.cereal.stockx.api.model.ProductSizeChart

class ProductTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Product
        //val modelInstance = Product()

        // to test the property `productId` - Unique identifier for a product
        should("test productId") {
            // uncomment below to test the property
            //modelInstance.productId shouldBe ("TODO")
        }

        // to test the property `urlKey` - The product name
        should("test urlKey") {
            // uncomment below to test the property
            //modelInstance.urlKey shouldBe ("TODO")
        }

        // to test the property `styleId` - ID of prduct style
        should("test styleId") {
            // uncomment below to test the property
            //modelInstance.styleId shouldBe ("TODO")
        }

        // to test the property `productType` - The type of product categories that are available on StockX
        should("test productType") {
            // uncomment below to test the property
            //modelInstance.productType shouldBe ("TODO")
        }

        // to test the property `title` - A string that uniquely identifies the product name.
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `brand` - Brand of the product
        should("test brand") {
            // uncomment below to test the property
            //modelInstance.brand shouldBe ("TODO")
        }

        // to test the property `productAttributes`
        should("test productAttributes") {
            // uncomment below to test the property
            //modelInstance.productAttributes shouldBe ("TODO")
        }

        // to test the property `sizeChart`
        should("test sizeChart") {
            // uncomment below to test the property
            //modelInstance.sizeChart shouldBe ("TODO")
        }

    }
}
