/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.PublicApiError
import com.cereal.stockx.api.model.HttpStatusCodeLiteral

class PublicApiErrorTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PublicApiError
        //val modelInstance = PublicApiError()

        // to test the property `statusCode`
        should("test statusCode") {
            // uncomment below to test the property
            //modelInstance.statusCode shouldBe ("TODO")
        }

        // to test the property `message` - The error message
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

    }
}
