/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.cereal.stockx.api.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.cereal.stockx.api.model.Variant

class VariantTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Variant
        //val modelInstance = Variant()

        // to test the property `variantId` - Unique identifier for a products variant
        should("test variantId") {
            // uncomment below to test the property
            //modelInstance.variantId shouldBe ("TODO")
        }

        // to test the property `variantName` - Unique readable name of the products variant
        should("test variantName") {
            // uncomment below to test the property
            //modelInstance.variantName shouldBe ("TODO")
        }

        // to test the property `variantValue` - The value of the variant. For example, in the sneakers case, this could be 10 or in the trading cards case, this could be PSA 10, etc.
        should("test variantValue") {
            // uncomment below to test the property
            //modelInstance.variantValue shouldBe ("TODO")
        }

    }
}
