name: Build script JAR

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ script-nike, script-snkrs, script-bdga-store ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build
        run:
          ./gradlew ${{ matrix.module }}:scriptJar
      - name: Store jar
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.module }}-${{ github.ref_name }}-release
          path: ${{ matrix.module }}/build/obfuscated/release.jar